# Generated by Django 4.1 on 2022-08-09 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.CharField(max_length=32, null=True)),
                ('start_date', models.DateField(blank=True, default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, default=datetime.date.today)),
                ('page_count', models.PositiveSmallIntegerField(default=0)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone_number', models.CharField(default='', max_length=16)),
                ('options', models.CharField(max_length=254, null=True)),
                ('content', models.TextField(null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
