# Generated by Django 4.1 on 2022-08-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_end_date_alter_order_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='page_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
