# Generated by Django 4.1 on 2022-08-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_page_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='page_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
